// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptionsPattern.Repository;

#nullable disable

namespace OptionsPattern.Migrations
{
    [DbContext(typeof(ErrorLoggerDbContext))]
    [Migration("20260323112536_TableUpdate")]
    partial class TableUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OptionsPattern.Models.ErrorLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<string>("Details")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("details");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("logged_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("method_name");

                    b.HasKey("LogId");

                    b.ToTable("errorlogs");
                });
#pragma warning restore 612, 618
        }
    }
}
